# Generated by Django 4.2.5 on 2023-09-26 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Used'), (2, 'Cancelled'), (3, 'Expired')], default=0)),
                ('amount', models.BigIntegerField()),
                ('payment_for', models.IntegerField(choices=[(0, 'Autosend'), (1, 'Search'), (2, 'All')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Полное имя')),
                ('username', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Имя пользователя')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Идентификатор телеграммы')),
                ('tel_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('status', models.CharField(blank=True, choices=[('maxsus', '✅ Спец. пользователь'), ('new_maxsus', '✅ Восст. Спец. пользователь'), ('student', '👨\u200d🏫 Студент'), ('new_student', '👨\u200d🏫 Восст. Студент'), ('graduate', '👨\u200d🎓 Старые студенты'), ('new_graduate', '👨\u200d🎓 Восст. Старые студенты')], max_length=30, null=True, verbose_name='Позиция')),
                ('kod', models.CharField(blank=True, max_length=15, null=True, verbose_name='Код доступа к боту')),
                ('my_kod', models.CharField(blank=True, max_length=15, null=True, verbose_name='Код восстановления')),
                ('isadmin', models.BooleanField(default=False, verbose_name='Админ')),
                ('lang', models.CharField(blank=True, choices=[('uz', 'узбекский'), ('ru', 'Русский')], default='uz', max_length=100, null=True, verbose_name='Язык бота')),
                ('start_data', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата регистрации')),
                ('balans1_avto', models.FloatField(blank=True, default=0, null=True, verbose_name='АвтоРассылки баланса')),
                ('balans2_yuk', models.FloatField(blank=True, default=0, null=True, verbose_name='Баланс поиска груза')),
                ('balans_ikkalasi', models.FloatField(blank=True, default=0, null=True, verbose_name='Баланс АвтоРассылки и Поиски груза')),
                ('valyuta', models.CharField(blank=True, default='UZS', max_length=100, null=True, verbose_name='Валюта')),
                ('podpiski1', models.DateTimeField(blank=True, null=True, verbose_name='"Автоотправку" времени подписки')),
                ('podpiski1_end', models.DateTimeField(blank=True, null=True, verbose_name='"Автоотправку" даты окончания подписки')),
                ('podpiski2', models.DateTimeField(blank=True, null=True, verbose_name='"Поиск груза" времени подписки')),
                ('podpiski2_end', models.DateTimeField(blank=True, null=True, verbose_name='"Поиск груза" даты окончания подписки')),
                ('tolov_avto_yuk', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Последний оплаченный раздел')),
                ('oxirgi_price', models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Сумма последнего платежа')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_app', models.CharField(choices=[('uzum', 'Uzum'), ('click', 'Click'), ('payme', 'Payme')], default='uzum', max_length=10)),
                ('transactionId', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment_api.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='payment_api.user'),
        ),
    ]
