# Generated by Django 4.2.5 on 2023-09-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_app',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_app',
            field=models.CharField(choices=[('uzum', 'Uzum'), ('click', 'Click'), ('payme', 'Payme')], default='uzum', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Paid'), (2, 'Cancelled'), (3, 'Expired')], default=0),
        ),
        migrations.CreateModel(
            name='ClickPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.BigIntegerField(unique=True)),
                ('action', models.IntegerField(choices=[(0, 'Preparing'), (1, 'Complete')], default=0)),
                ('sign_time', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_payment', to='payment_api.order')),
            ],
        ),
    ]
