# Generated by Django 4.2.5 on 2023-09-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0002_remove_payment_payment_app_order_payment_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickpayment',
            name='transactionId',
            field=models.BigIntegerField(),
        ),
    ]
