# Generated by Django 4.2.5 on 2023-10-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0003_alter_clickpayment_transactionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(blank=True, choices=[('avtorassilka', 'АвтоРассылки'), ('poiskgruzov', 'Поиски грузов'), ('ikkalasi', 'Оба из них')], max_length=30, null=True, verbose_name='Тип возможности')),
                ('month', models.CharField(blank=True, choices=[('3', '3 день'), ('5', '5 день'), ('7', '7 день'), ('15', '15 день'), ('30', '1 месяц'), ('60', '2 месяц'), ('90', '3 месяц'), ('120', '4 месяц'), ('150', '5 месяц'), ('180', '6 месяц'), ('210', '7 месяц'), ('240', '8 месяц'), ('270', '9 месяц'), ('300', '10 месяц'), ('330', '11 месяц'), ('360', '1 год'), ('720', '2 год')], max_length=30, null=True, verbose_name='Количество дней')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена (в сумах)')),
                ('chegirma', models.CharField(blank=True, max_length=20, null=True, verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Uzum payment', 'verbose_name_plural': 'Uzum payments'},
        ),
        migrations.AddField(
            model_name='user',
            name='send_group_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на группу отправлена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_app',
            field=models.CharField(choices=[('none', 'None'), ('uzum', 'Uzum'), ('click', 'Click'), ('payme', 'Payme')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('maxsus', '✅ Спец. пользователь'), ('new_maxsus', '✅ Восст. Спец. пользователь'), ('student', '👨\u200d🏫 Студент'), ('new_student', '👨\u200d🏫 Восст. Студент'), ('graduate', '👨\u200d🎓 Старые студенты'), ('new_graduate', '👨\u200d🎓 Восст. Старые студенты')], max_length=100, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.CreateModel(
            name='PayMeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_action_time', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payme_payments', to='payment_api.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tariff',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff_payments', to='payment_api.tarif'),
        ),
    ]
