# Generated by Django 4.2.5 on 2023-10-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0006_alter_paymetransaction_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clickpayment',
            options={'verbose_name': 'Click', 'verbose_name_plural': 'Click'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Uzum', 'verbose_name_plural': 'Uzum'},
        ),
        migrations.AlterModelOptions(
            name='paymetransaction',
            options={'verbose_name': 'PayMe', 'verbose_name_plural': 'PayMe'},
        ),
        migrations.RenameField(
            model_name='paymetransaction',
            old_name='last_action_time',
            new_name='cancel_time',
        ),
        migrations.AddField(
            model_name='paymetransaction',
            name='perform_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
