# Generated by Django 4.2.5 on 2023-10-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0007_alter_clickpayment_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymetransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payme_transactions', to='payment_api.order'),
        ),
    ]
