# Generated by Django 4.2.5 on 2023-11-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0009_remove_paymetransaction_time_paymetransaction_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymetransaction',
            name='cancel_time',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymetransaction',
            name='create_time',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymetransaction',
            name='perform_time',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
